apiVersion: v1
kind: Service
metadata:
  name: agent-meow
  labels:
    app: agent-meow
spec:
  type: ClusterIP
  selector:
    app: agent-meow
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
