"""add session_projects table

Revision ID: 5c5fe73e94bd
Revises: 8bd8a16f9570
Create Date: 2026-07-26 10:19:33.697906
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5fe73e94bd'
down_revision: Union[str, None] = '8bd8a16f9570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_projects_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_session_projects_updated_at', ['updated_at'], unique=False)

    with op.batch_alter_table('conversation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_items_conv_type_position'))
        batch_op.create_index('ix_conversation_items_conv_type_position', ['workspace_id', 'conversation_id', 'type', sa.literal_column('position DESC')], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_conversations_parent'))
        batch_op.create_index('idx_conversations_parent', ['workspace_id', 'parent_conversation_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('handler',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.alter_column('handler',
               existing_type=sa.BLOB(),
               nullable=True)

    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversations_parent')
        batch_op.create_index(batch_op.f('idx_conversations_parent'), ['workspace_id', 'parent_conversation_id', 'created_at', 'id'], unique=False)

    with op.batch_alter_table('conversation_items', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_items_conv_type_position')
        batch_op.create_index(batch_op.f('ix_conversation_items_conv_type_position'), ['workspace_id', 'conversation_id', 'type', 'position'], unique=False)

    with op.batch_alter_table('session_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_session_projects_updated_at')
        batch_op.drop_index(batch_op.f('ix_session_projects_conversation_id'))

    op.drop_table('session_projects')
    # ### end Alembic commands ###
