apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: agent-meow
  labels:
    app: agent-meow
spec:
  host: agent_meow.apps.example.com
  to:
    kind: Service
    name: agent-meow
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
